config/routes.rb
Tetris::Application.routes.draw do

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :scores, only: [:create]

  root to: 'static_pages#home'
  get '/about' => 'static_pages#about', as: :about
  delete '/signout', to: 'sessions#destroy'
  get "*path" => redirect("/")

end

app/models/score.rb
class Score < ActiveRecord::Base

  belongs_to :user

  validates :user_id, :points, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save :create_remember_token
  before_save { email.downcase! }

  has_secure_password

  has_many :scores

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def create
    @score = Score.new(points: params["score"])
    current_user.scores << @score
    if @score.save
      render json: @score
    end
  end

  private

    def score_params
      params.require(:score).permit(:points)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render layout: false
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash[:error] = "Invalid email/password combination"
      render 'new', layout: 'application'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    scores = Score.order('points DESC').limit(5)
    @top_scores = []
    scores.each do |score|
      @top_scores << score.user.name
      @top_scores << score.points
    end
  end

  def about
    render layout: false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render layout: false
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    binding.pry
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tetris</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/flash_messages' %>
	<div id='gray_border'>
    <div id='matrix'>
      <div id='left_lines'>
        <div id='left_pink'></div>
        <div id='left_purple'></div>
      </div>
      <p>DOT MATRIX WITH STEREO SOUND</p>
      <div id='right_lines'>
        <div id='right_pink'></div>
        <div id='right_purple'></div>
      </div>
    </div>
    <div id='battery'>
      <div id='battery_indicator'></div>
      <p>BATTERY</p>
    </div>
    <div id='main'>
      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_top_scores.html.erb
<div id="topScores" class="center">
	<p>Top Scores</p>
	<ul>
		<% @top_scores.each_with_index do |i, index| %>
			<% if index % 2 != 0 %>
				<% next %>
			<% end %>
			<li><%= i %>: <%= @top_scores[index + 1] %></li>
		<% end %>
	</ul>
</div>

app/views/static_pages/_main_menu.html.erb
<div id='mainMenu'>
	<%= link_to "Log In", new_session_path, remote: true, id: 'main_menu_login', class: 'button' %>
	<%= link_to "Create a New Account", new_user_path, remote: true, id: 'mainMenuCreate', class: 'button' %>
	<%= link_to "About", about_path, remote: true, id: 'mainMenuAbout', class: 'button' %>
  <%= render 'shared/top_scores' %>
</div>

app/views/static_pages/about.html.erb
<div id='about'>
  <h3>About This Game</h3>
  <p>This game is a recreation of the 1989 Game Boy classic created by Alexey Pajitnov in 1984. Tetris almost single handedly "made Game Boy" when it became bundled with every console. This recreation was coded by 
  <%= link_to 'Jimmy Wong', 'https://github.com/jimwong1023/', target: '_blank' %>.</p>

  <p>I'd like to thank my friend <%= link_to 'Dan Apczynski', 'http://danapczynski.com', target: '_blank' %> for giving me the inspiration to start on this project and for allowing me to use his awesome Game Boy CSS!</p>
  
  <%= link_to "View on Github", 'https://github.com/jimwong1023/tetris', target: '_blank', class: 'button' %>
  <%= link_to "Go Back", root_path, class: 'button' %>
</div>

app/views/static_pages/home.html.erb
<div id="board">
		<% if signed_in? %>
			<div id='mainMenu'>
				<h1 id='gameTitle'>Tetris</h1>
				<h3 id="welcome">Welcome <%= current_user.name %>!</h3>
				<div class="startGame button">Start Game</div>
				<%= link_to "Sign out", signout_path, method: "delete", class: 'button' %>
				<%= render 'shared/top_scores' %>
			</div>
			<div id="canvasContainer" class="hidden">
			  <canvas id="canvas" width="300" height="600"></canvas>
			  <div id="gameInfo">
			  	<p class="level">Level: <span>1</span></p>
			  	<p class="score">Score: <span >0</span></p>
			  </div>
			</div>
			<div id="gameOver" class="hidden">
				<h1 id='gameTitle'>GAME OVER!</h1>
				<div>
			  	<p class="level">Level: <span>1</span></p>
			  	<p class="score">Score: <span>0</span></p>
			  	<div class="startGame button">Play Again?</div>
			  	<%= link_to "Sign out", signout_path, method: "delete", class: 'button' %>
			  </div>
			</div>
		<% else %>
			<h1 id='gameTitle'>Tetris</h1>
		  <%= render 'main_menu' %>
		<% end %>
</div>

app/views/users/new.html.erb
<div id='newUserForm' class='form-div'>
  <h3>Create a User</h3>
  <%= form_for @user do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit 'Done', remote: true, id: 'submit-new_user-button', class: 'submit-button' %>
  <% end %>
  <%= link_to "Go Back", root_path, class: 'button' %>
</div>